// samples/music-festival-react-coupled/ClientApp/src/components/Card/Card.tsx
import styles from './Card.module.scss';

import React, { ReactElement } from 'react';
import ConditionalImage from '../ConditionalImage';
import EpiserverLink from '../EpiserverLink';
import { CardProps } from './CardProps';

const Card = ({ name, image, url }: CardProps): ReactElement => {
    return (
        <EpiserverLink url={url}>
            <div className={styles.card}>
                <div className={styles.round}>
                    <ConditionalImage
                        src={process.env.NEXT_PUBLIC_WEBSITE_URL + image}
                        alt={name}
                        width={60}
                        height={60}
                    />
                </div>
                <div className={styles.info}>
                    <p>{name}</p>
                </div>
            </div>
        </EpiserverLink>
    );
};

export default React.memo(Card);

// samples/music-festival-react-coupled/ClientApp/old-vue/components/Card.vue
<script setup>
defineProps(['name', 'image', 'url']);
</script>

<template>
    <EpiserverLink :url="url">
        <div class="card">
            <div class="round">
                <ConditionalImage :src="image" :alt="name" />
            </div>
            <div class="info">
                <p>{{ name }}</p>
            </div>
        </div>
    </EpiserverLink>
</template>

<style lang="less" scoped>
@import '../assets/styles/common/variables.less';

.card {
    display: flex;
    flex-direction: row;
    align-items: center;
    padding: 10px 30px 10px 25px;
}
.round {
    width: 40px;
    height: 40px;
    border-radius: 40px;
    overflow: hidden;
    margin-right: 10px;
    img {
        max-width: 150%;
        margin-left: -15px;
    }

    &.big {
        width: 60px;
        height: 60px;
    }
}
.info {
    flex-grow: 1;
    p {
        margin: 0;
        font: 14px/20px @fontSubHeading;
    }
    span {
        display: block;
        font: 12px/16px @fontFamilyPrimary;
    }
}
</style>
