// samples/music-festival-react-coupled/ClientApp/src/components/Hero/Hero.tsx
import { addEditAttributes } from '@/utils/episerverAttributes';
import React, { ReactElement } from 'react';
import EpiserverProperty from '../EpiserverProperty';
import styles from './Hero.module.scss';
import HeroProps from './HeroProps';

const Hero = ({ title, subtitle, heroimage }: HeroProps): ReactElement => {
    // const { active as modalActive } = useModal();
    const modalActive = false;

    return (
        <section className={styles.Hero}>
            <div className={`${styles.HeroContent} Page-container`}>
                <h1
                    {...addEditAttributes('Title')}
                    dangerouslySetInnerHTML={{ __html: title }}
                ></h1>
                <h5
                    {...addEditAttributes('Subtitle')}
                    dangerouslySetInnerHTML={{ __html: subtitle }}
                ></h5>
                {!modalActive && <EpiserverProperty propertyName="HeroImage" />}
            </div>
            {heroimage && (
                <div
                    className={styles.HeroImage}
                    style={{ backgroundImage: `url(${heroimage})` }}
                />
            )}
        </section>
    );
};

export default React.memo(Hero);

// samples/music-festival-react-coupled/ClientApp/old-vue/components/Hero.vue
<script setup>
defineProps(['title', 'subtitle', 'heroimage']);
const { active: modalActive } = useModal();
</script>

<template>
    <section class="Hero">
        <div class="Hero-content Page-container">
            <h1 v-epi-edit="'Title'" v-html="title"></h1>
            <h5 v-epi-edit="'Subtitle'" v-html="subtitle"></h5>
            <EpiserverProperty
                v-show="!modalActive"
                property-name="HeroImage"
            />
        </div>
        <div
            class="Hero-image"
            v-if="heroimage"
            :style="{ 'background-image': 'url(' + heroimage + ')' }"
        ></div>
    </section>
</template>
