// samples/music-festival-react-coupled/ClientApp/old-vue/views/pages/LandingPage.vue
<script setup>
defineProps(['model']);
const { showModal } = useModal();
</script>

<template>
    <div class="LandingPage">
        <nav class="Page-container PageHeader NavBar">
            <button class="Button buy-ticket-button" @click="showModal()">
                {{ model.buyTicketBlock.heading }}
            </button>

            <LanguageSelector
                :existingLanguages="model.existingLanguages"
                :language="model.language"
            />
        </nav>

        <Hero
            :title="model.title"
            :subtitle="model.subtitle"
            :heroimage="model.heroImage"
        />

        <EpiserverLink
            :url="model.artistsLink.expanded.url"
            :class-name="'Button modal-default-button landing-page-button'"
        >
            {{ model.artistsLink.expanded.name }}
        </EpiserverLink>

        <main class="Page-container">
            <div v-epi-edit="'MainContentArea'">
                <EpiserverContentArea :model="model.mainContentArea" />
            </div>
        </main>

        <footer>
            <div v-epi-edit="'FooterContentArea'">
                <EpiserverContentArea :model="model.footerContentArea" />
            </div>
            <div class="FooterBottom">
                <h6>&copy; Music Festival 2022</h6>
            </div>
        </footer>

        <Modal>
            <template v-slot:content>
                <BuyTicketBlock
                    :page-property-name="'BuyTicketBlock'"
                    :heading="model.buyTicketBlock.heading"
                    :message="model.buyTicketBlock.message"
                />
            </template>
        </Modal>
    </div>
</template>

<style lang="less">
@import '../../assets/styles/common/variables.less';

main,
footer {
    overflow: hidden;
    width: 100%;
}

footer .ContentArea.Grid--gutterA {
    // Disable gutters because we want this content area to be full width.
    margin: 0;
}

.landing-page-button {
    position: absolute;
    left: 50%;
    transform: translateX(-50%);
    margin-top: 1em;
}

.buy-ticket-button {
    margin-top: 11px;
}
</style>

// samples/music-festival-react-coupled/ClientApp/src/pages/LandingPage/LandingPage.tsx
import EpiserverLink from '@/components/EpiserverLink';
import styles from './LandingPage.module.scss';

import EpiserverContentArea from '@/components/EpiserverContentArea';
import Hero from '@/components/Hero';
import LanguageSelector from '@/components/LanguageSelector';
import { addEditAttributes } from '@/utils/episerverAttributes';
import React, { ReactElement } from 'react';
import LandingPageProps from './LandingPageProps';

const LandingPage = ({ content }: LandingPageProps): ReactElement => {
    // const { showModal } = useModal();
    return (
        <div className={styles.LandingPage}>
            <nav className="Page-container PageHeader NavBar">
                <button
                    className="Button buy-ticket-button"
                    // onClick={showModal()}
                >
                    {content.buyTicketBlock.heading}
                </button>

                <LanguageSelector
                    existingLanguages={content.existingLanguages}
                    language={content.language}
                />
            </nav>

            <Hero
                title={content.title}
                subtitle={content.subtitle}
                heroimage={content.heroImage}
            />

            <EpiserverLink
                url={content.artistsLink.expanded.url}
                className="Button modal-default-button landing-page-button"
            >
                {content.artistsLink.expanded.name}
            </EpiserverLink>

            <main className="Page-container">
                <div {...addEditAttributes('MainContentArea')}>
                    <EpiserverContentArea content={content.mainContentArea} />
                </div>
            </main>

            <footer>
                <div {...addEditAttributes('FooterContentArea')}>
                    <EpiserverContentArea content={content.footerContentArea} />
                </div>
                <div className="FooterBottom">
                    <h6>&copy; Music Festival 2022</h6>
                </div>
            </footer>
            {/*
                <Modal>
                    <template v-slot:content>
                        <BuyTicketBlock
                            :page-property-name="'BuyTicketBlock'"
                            :heading="model.buyTicketBlock.heading"
                            :message="model.buyTicketBlock.message"
                        />
                    </template>
                </Modal>
            */}
        </div>
    );
};
export default React.memo(LandingPage);
