// samples/music-festival-react-coupled/ClientApp/old-vue/views/blocks/ContentBlock.vue
<script setup>
const props = defineProps(['model']);

const imageAlignment = computed(() => {
    if (props.model.imageAlignment === 'Right') {
        return 'Grid--rowReverse';
    }
    return null;
});
</script>

<template>
    <div class="Page-container ContentBlock">
        <div
            class="Grid Grid--alignMiddle Grid--gutterA"
            :class="imageAlignment"
        >
            <div class="Grid-cell u-md-size1of2" v-if="model.image">
                <ConditionalImage
                    :src="model.image"
                    :alt="model.title"
                    v-epi-edit="'Image'"
                />
            </div>
            <div class="Grid-cell" :class="{ 'u-md-size1of2': model.image }">
                <h2 v-epi-edit="'Title'">{{ model.title }}</h2>
                <div v-epi-edit="'Content'" v-html="model.content"></div>
                <EpiserverProperty v-if="!model.image" property-name="image" />
            </div>
        </div>
    </div>
</template>

// samples/music-festival-react-coupled/ClientApp/src/components/ContentBlock/ContentBlock.tsx
import classNames from '@/utils/classNames';
import { addEditAttributes } from '@/utils/episerverAttributes';
import React, { ReactElement } from 'react';
import ConditionalImage from '../ConditionalImage';
import EpiserverProperty from '../EpiserverProperty';
import ContentBlockProps from './ContentBlockProps';

const ContentBlock = ({ content }: ContentBlockProps): ReactElement => {
    const imageAlignment =
        content.imageAlignment === 'Right' ? 'Grid--rowReverse' : undefined;

    return (
        <div className="Page-container ContentBlock">
            <div
                className={classNames([
                    'Grid Grid--alignMiddle Grid--gutterA',
                    imageAlignment,
                ])}
            >
                {content.image && (
                    <div className="Grid-cell u-md-size1of2">
                        <ConditionalImage
                            src={
                                process.env.NEXT_PUBLIC_WEBSITE_URL +
                                content.image
                            }
                            alt={content.title}
                            width={1000}
                            height={1000}
                            {...addEditAttributes('Image')}
                        />
                    </div>
                )}
                <div
                    className={classNames([
                        'Grid-cell',
                        content.image ? 'u-md-size1of2' : undefined,
                    ])}
                >
                    <h2 {...addEditAttributes('Title')}>{content.title}</h2>
                    <div
                        {...addEditAttributes('Content')}
                        dangerouslySetInnerHTML={{ __html: content.content }}
                    />
                    {!content.image && (
                        <EpiserverProperty propertyName="image" />
                    )}
                </div>
            </div>
        </div>
    );
};

export default React.memo(ContentBlock);
