// samples/music-festival-react-coupled/ClientApp/old-vue/views/media/ImageFile.vue
<script setup>
defineProps(['model']);
</script>

<template>
    <div class="Page-container ImageFile">
        <div class="Grid Grid--alignMiddle Grid--gutterA">
            <div class="Grid-cell">
                <ConditionalImage :src="model.url" />
            </div>
        </div>
    </div>
</template>

// samples/music-festival-react-coupled/ClientApp/src/components/ImageFile/ImageFile.tsx
import { ReactElement } from 'react';
import ConditionalImage from '../ConditionalImage';
import ImageFileProps from './ImageFileProps';

const ImageFile = ({ content }: ImageFileProps): ReactElement => {
    return (
        <div className="Page-container ImageFile">
            <div className="Grid Grid--alignMiddle Grid--gutterA">
                <div className="Grid-cell">
                    <ConditionalImage
                        src={process.env.NEXT_PUBLIC_WEBSITE_URL + content.url}
                        alt=""
                        width={500}
                        height={500}
                    />
                </div>
            </div>
        </div>
    );
};

export default ImageFile;
