// samples/music-festival-react-coupled/ClientApp/old-vue/views/blocks/BuyTicketBlock.vue
<script setup>
const props = defineProps(['pagePropertyName', 'model', 'heading', 'message']);

function prefixPropertyName(propertyName) {
    return props.pagePropertyName
        ? `${props.pagePropertyName}.${propertyName}`
        : propertyName;
}
</script>

<template>
    <div class="buyTickets-container">
        <h3 v-epi-edit="prefixPropertyName('Heading')">
            {{ heading || model.heading }}
        </h3>
        <div>
            <label
                for="tickets-email"
                v-epi-edit="prefixPropertyName('Message')"
            >
                {{ message || model.message }}
                <input id="tickets-email" type="email" />
            </label>
        </div>
    </div>
</template>

<style lang="less" scoped>
@import '../../assets/styles/common/variables.less';

.buyTickets-container {
    background: @backgroundColor;
    padding: @space;
    border-radius: 1em;
}
</style>

// samples/music-festival-react-coupled/ClientApp/src/components/BuyTicketBlock/BuyTicketBlock.tsx
import styles from './BuyTicketBlock.module.scss';

import { addEditAttributes } from '@/utils/episerverAttributes';
import React, { ReactElement } from 'react';
import BuyTicketBlockProps from './BuyTicketBlockProps';

const BuyTicketBlock = ({
    heading,
    message,
    pagePropertyName,
}: BuyTicketBlockProps): ReactElement => {
    const prefixPropertyName = (propertyName: string): string => {
        return pagePropertyName
            ? `${pagePropertyName}.${propertyName}`
            : propertyName;
    };

    return (
        <div className={styles.buyTickets}>
            <h3 {...addEditAttributes(prefixPropertyName('Heading'))}>
                {heading || ''}
            </h3>
            <div>
                <label
                    htmlFor="tickets-email"
                    {...addEditAttributes(prefixPropertyName('Message'))}
                >
                    {message || ''}
                    <input id="tickets-email" type="email" />
                </label>
            </div>
        </div>
    );
};

export default React.memo(BuyTicketBlock);
