// samples/music-festival-react-coupled/ClientApp/old-vue/components/BackButton.vue
<script setup>
defineProps(['previousUrl']);
</script>

<template>
    <div v-if="previousUrl" class="backButton">
        <EpiserverLink :url="previousUrl">
            <img src="~/assets/images/back.svg" width="64" height="64" alt="" />
        </EpiserverLink>
    </div>
</template>

<style lang="less" scoped>
.backButton {
    z-index: 10;
    height: 50px;
    width: 50px;
    margin-top: 7px;
}

@media (min-width: 768px) {
    .backButton {
        height: 64px;
        width: 64px;
        margin-top: 0;
    }
}
</style>

// samples/music-festival-react-coupled/ClientApp/src/components/BackButton/BackButton.tsx
import styles from './BackButton.module.scss';

import Image from 'next/image';
import React, { ReactElement } from 'react';
import EpiserverLink from '../EpiserverLink';
import { BackButtonProps } from './BackButtonProps';

const BackButton = ({ previousUrl }: BackButtonProps): ReactElement => {
    return (
        <div className={styles.backButton}>
            <EpiserverLink url={previousUrl} className={styles.link}>
                <Image src="/back.svg" width="64" height="64" alt="Back" />
            </EpiserverLink>
        </div>
    );
};

export default React.memo(BackButton);
