// samples/music-festival-react-coupled/ClientApp/old-vue/components/ArtistImage.vue
<script setup>
defineProps(['name', 'imageUrl']);
</script>

<template>
    <div class="artistImage">
        <div>
            <ConditionalImage :src="imageUrl" :alt="name" />
        </div>
    </div>
</template>

<style lang="less" scoped>
.artistImage {
    padding-top: 80px;
}

img {
    width: 100%;
    height: auto;
    animation: fadein 2s;
}

@keyframes fadein {
    from {
        opacity: 0;
    }
    to {
        opacity: 1;
    }
}
</style>

// samples/music-festival-react-coupled/ClientApp/src/components/ArtistImage/ArtistImage.tsx
import styles from './ArtistImage.module.scss';

import React, { ReactElement } from 'react';
import { ArtistImageProps } from './ArtistImageProps';
import ConditionalImage from '../ConditionalImage';

const ArtistImage = ({ imageUrl, name }: ArtistImageProps): ReactElement => {
    return (
        <div className={styles.artistImage}>
            <div>
                <ConditionalImage
                    src={process.env.NEXT_PUBLIC_WEBSITE_URL + imageUrl}
                    alt={name}
                    width={2000}
                    height={2000}
                />
            </div>
        </div>
    );
};

export default React.memo(ArtistImage);
