// samples/music-festival-react-coupled/ClientApp/old-vue/views/pages/ArtistContainerPage.vue
<script setup>
import { ContentLoader } from '@episerver/content-delivery';

const props = defineProps(['model']);
const artists = ref({});

onBeforeMount(() => {
    const contentLoader = new ContentLoader();
    contentLoader
        .getChildren(props.model.contentLink.guidValue, {
            branch: props.model.language.name,
        })
        .then((children) => {
            const ordered = children.sort(
                (a, b) =>
                    a.artistName.toLowerCase() < b.artistName.toLowerCase()
            );

            // Group by first letter of artist name
            artists.value = ordered.reduce((groups, item) => {
                const letter = item.artistName.substring(0, 1);
                groups[letter] = groups[letter] || [];
                groups[letter].push(item);
                return groups;
            }, {});
        });
});
</script>

<template>
    <div class="ArtistContainerPage">
        <nav class="Page-container PageHeader NavBar">
            <BackButton :previousUrl="model.parentLink.url" />
            <LanguageSelector
                :existingLanguages="model.existingLanguages"
                :language="model.language"
            />
        </nav>

        <div class="Page-container">
            <div class="top gutter">
                <h1 v-epi-edit="'Name'">{{ model.name }}</h1>
            </div>
            <div class="list">
                <div v-for="(value, key) in artists" :key="key">
                    <h3>{{ key }}</h3>
                    <Card
                        v-for="(value, key) in value"
                        :key="key"
                        :name="value.artistName"
                        :image="value.artistPhoto"
                        :url="value.url"
                    />
                </div>
            </div>
        </div>

        <footer>
            <div class="FooterBottom">
                <h6>&copy; Music Festival 2022</h6>
            </div>
        </footer>
    </div>
</template>

<style lang="less" scoped>
.top h1 {
    text-transform: none;
    margin: 0 40px 0 40px;
    padding: 0.3em 0;

    @media (min-width: 425px) {
        margin-right: 140px;
    }
}
h3 {
    text-transform: uppercase;
    width: 100%;
    text-align: center;
    background: rgba(236, 64, 122, 0.24);
    padding: 5px 0 7px;
    margin: 0;
}
</style>

// samples/music-festival-react-coupled/ClientApp/src/pages/ArtistContainerPage/ArtistContainerPage.tsx
import Card from '@/components/Card';
import EpiContent from '@/types/EpiContent';
import { ContentLoader } from '@episerver/content-delivery';
import { ReactElement, useState } from 'react';
import { ArtistDetailsPage } from '../ArtistDetailsPage/ArtistDetailsPageProps';

const ArtistContainerPage = ({ content }: EpiContent): ReactElement => {
    const [artists, setArtists] = useState<[string, ArtistDetailsPage[]][]>([]);
    const [loading, setLoading] = useState(true);
    const contentLoader = new ContentLoader();

    if (loading)
        contentLoader
            .getChildren<ArtistDetailsPage>(content.contentLink.guidValue, {
                branch: content.language.name,
            })
            .then((children) => {
                const ordered: ArtistDetailsPage[] = children.sort(
                    (a, b): number =>
                        a.artistName.toLowerCase() < b.artistName.toLowerCase()
                            ? -1
                            : 1
                );

                // Group by first letter of artist name
                const artistsByLetter = ordered.reduce(
                    (
                        groups: {
                            [key: string]: ArtistDetailsPage[];
                        },
                        item: ArtistDetailsPage
                    ) => {
                        const letter = item.artistName.substring(0, 1);
                        groups[letter] = groups[letter] || [];
                        groups[letter].push(item);
                        return groups;
                    },
                    {}
                );
                setArtists(Object.entries(artistsByLetter));
            })
            .finally(() => setLoading(false));

    return (
        <div className="ArtistContainerPage">
            <nav className="Page-container PageHeader NavBar">
                {/*

                <BackButton previousUrl={content.parentLink.url} />
                <LanguageSelector
                    existingLanguages={content.existingLanguages}
                    language={content.language}
                />

                */}
            </nav>

            <div className="Page-container">
                <div className="top gutter">
                    <h1 v-epi-edit="'Name'">{content.name}</h1>
                </div>
                <div className="list">
                    {artists &&
                        artists.map((artist) => {
                            const [key, values] = artist;
                            return (
                                <div key={key}>
                                    <h3>{key}</h3>
                                    {values.map((value, key) => (
                                        <Card
                                            v-for="(value, key) in value"
                                            key={key}
                                            name={value.artistName}
                                            image={value.artistPhoto}
                                            url={value.url}
                                        />
                                    ))}
                                </div>
                            );
                        })}
                </div>
            </div>

            <footer>
                <div className="FooterBottom">
                    <h6>&copy; Music Festival 2022</h6>
                </div>
            </footer>
        </div>
    );
};

export default ArtistContainerPage;
